config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :places

  namespace :api do
    namespace :v1 do
      resources :places, only: [:index, :show]
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
  def self.to_csv
    attributes = ['id', 'en_name', 'en_description', 'category', 'es_name', 'es_description', 'lat', 'lon']
    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |user|
        csv << user.attributes.values_at(*attributes)
      end
    end
  end

  def self.output_csv(filename)
    File.open("tmp/#{filename}", 'w') { |f| f.write(to_csv) }
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :email, format: { with: /\S+@\S+/ }, uniqueness: { case_sensitive: false }
end

app/controllers/api/v1/places_controller.rb
class Api::V1::PlacesController < ApplicationController
  def index
    @places = Place.all
    render json: @places #each_serializer: Api::V1::PropSerializer
  end

  def show
    @place = Place.find(params[:id])
    render json: @places
  end

  private

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def require_signin
    return if current_user

    redirect_to new_session_url, alert: 'Sign in required'
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :require_signin

  def index
    @places = Place.all
    respond_to do |format|
      format.json { render json: @places }
      format.html
      format.csv { send_data @places.to_csv }
    end
  end

  def show
    @place = Place.find(params[:id])
  end

  def new
    @place = Place.new
  end

  def edit
    @place = Place.find(params[:id])
  end

  def create
    @place = Place.new(place_params)
    @place.save!
    redirect_to @place
  end

  def update
    @place = Place.find(params[:id])
    @place.update(place_params)
    redirect_to @place
  end

  def destroy
    @place = Place.find(params[:id])
    @place.destroy!
    redirect_to root_path
  end

  private

  def place_params
    params.require(:place).permit(:en_name,
                                  :es_name,
                                  :en_description,
                                  :es_description,
                                  :category,
                                  :lat,
                                  :lon, 
                                  :remote_img)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      puts "Found User"
      session[:user_id] = user.id
      redirect_to root_path, notice: "Welcome Back, #{user.name}!"
    else
      flash.now[:alert] = "Invalid email/password combination."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "You are now signed out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @place_count = Place.count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PmaRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/places/_form.html.erb
<%= form_with(model: @place, local: true) do |f| %>
  <div class="field">
    <%= f.label :en_name %>
    <%= f.text_field :en_name %>
  </div>

  <div class="field">
    <%= f.label :es_name %>
    <%= f.text_field :es_name %>
  </div>

  <div class="field">
    <%= f.label :en_description %>
    <%= f.text_area :en_description %>
  </div class="field">

  <div class="field">
    <%= f.label :es_description %>
    <%= f.text_area :es_description %>
  </div class="field">

  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div class="field">
    <%= f.label :lat %>
    <%= f.text_field :lat %>
  </div>

  <div class="field">
    <%= f.label :lon %>
    <%= f.text_field :lon %>
  </div>

  <div class="field">
    <%= f.label :remote_img %>
    <%= f.text_field :remote_img %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<table >
  <thead>
    <tr >
      <th>ID</th>
      <th>Name</th>
      <th>Description</th>
      <th>Category</th>
      <th>Lat</th>
      <th>Long</th>
      <th>Has Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody >
    <% @places.each do |place| %>
      <tr>
        <td colspan="100%"><hr/></td>
      </tr>
      <tr>
        <td><%= place.id %> </td>
        <td><%= link_to place.en_name, place %></td>
        <td><%= place.en_description %></td>
        <td><%= place.category %></td>
        <td><%= place.lat %></td>
        <td><%= place.lon %></td>
        <td><%= place.remote_img.present? ? 'Yes' : 'No' %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <tr>
        <td></td>
        <td><%= place.es_name %></td>
        <td><%= place.es_description %></td>
        <td colspan="7"></td>
      </tr>      
    <% end %>
    
  </tbody>
</table>
<br>
<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Places', places_path %> | 
<%= @place.en_name %> |
<%= link_to 'Edit', edit_place_path(@place) %> 

<p>
  <strong>Title (EN):</strong>
  <%= @place.en_name %>
</p>

<p>
  <strong>Title (ES):</strong>
  <%= @place.es_name %>
</p>

<p>
  <strong>Description (EN):</strong>
  <%= @place.en_description %>
</p>

<p>
  <strong>Description (ES):</strong>
  <%= @place.es_description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @place.category %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @place.lat %>
</p>

<p>
  <strong>Longituge:</strong>
  <%= @place.lon %>
</p>

<p>
  <strong>Remote Image URL:</strong>
  <%= @place.remote_img %>
</p>

app/views/welcome/index.html.erb
<h2>PMA Backend</h2>
<% if current_user %>
  <p>
    There are currently <%= @place_count %> places in the system.
  </p>
  <p><%= link_to "Places", places_path %></p>
  <%= link_to "Sign Out", session_path, method: :delete %>
<% else %>
  <%= link_to "Sign In", new_session_path %>
<% end %>
</p>